name: QAChat
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - numpy
      - openai
      - selenium
      - slack_sdk
      - atlassian-python-api
      - langchain
      - panda
      - slackclient
      - supabase
      - InstructorEmbedding
      - sentence-transformers
      - slack-bolt
      - slack-sdk
      - deepl
      - llama-cpp-python
      - python-dotenv
      - pandas
      - huggingface_hub
      - typing_extensions==4.6.0
      - pdfminer.six
      - pytesseract
      - nltk