name: QAChat
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - openai
  - selenium
  - slack_sdk
  - pip=21.2.4
  - pip:
      - atlassian-python-api
      - langchain
      - panda
      - slackclient
      - supabase
      - InstructorEmbedding
      - sentence-transformers
      - slack-bolt
      - slack-sdk
      - deepl
