name: run-unit-test
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: run unit test
        run: |
             ls 
             python -c "print('Hello, World')"