name: run-unit-test-and-lint
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'Deliverables/**'
      - 'Documentation/**'
      - 'DummyData/**'
      - 'QAChat/**'

jobs:
  unit-tests-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install flake8 pytest langchain huggingface_hub supabase

      - name: Run unit tests
        run: pytest


      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true

